# Generated by Django 5.0.4 on 2024-06-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=44)),
                ('middle_name', models.CharField(max_length=44, null=True)),
                ('last_name', models.CharField(max_length=44, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=44, null=True)),
                ('phone', models.CharField(max_length=44, null=True)),
            ],
        ),
    ]
