# Generated by Django 5.0.4 on 2024-07-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_college_bdc_item_business_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='birthday',
            field=models.DateField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='blood_type',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='citizenship',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='civil_status',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='firstname',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lastname',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='middlename',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='mobile',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='perm_zip_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='telephone',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='zip_code',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
    ]
