from django.db import models

# Create your models here.
 
class Item(models.Model):
    firstname = models.CharField(max_length=44, null=True, blank=True)
    middlename = models.CharField(max_length=44, null=True, blank=True)
    lastname = models.CharField(max_length=44, null=True, blank=True)
    birthday = models.DateField(max_length=44, null=True, blank=True)
    place_of_birth = models.CharField(max_length=255, null=True, blank=True)
    sex = models.CharField(max_length=44, null=True, blank=True)
    civil_status = models.CharField(max_length=44, null=True, blank=True)
    height = models.CharField(max_length=44, null=True, blank=True)
    weight = models.CharField(max_length=44, null=True, blank=True)
    blood_type = models.CharField(max_length=44, null=True, blank=True)
    gsis_id = models.CharField(max_length=44, null=True, blank=True)
    pagibig_id = models.CharField(max_length=44, null=True, blank=True)
    philhealth = models.CharField(max_length=44, null=True, blank=True)
    sss = models.CharField(max_length=44, null=True, blank=True)
    tin = models.CharField(max_length=44, null=True, blank=True,)
    agency_emp = models.CharField(max_length=44, null=True, blank=True)
    citizenship = models.CharField(max_length=44, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    zip_code = models.CharField(max_length=44, null=True, blank=True)
    permanent_address = models.CharField(max_length=255, null=True, blank=True)
    perm_zip_code = models.CharField(max_length=255, null=True, blank=True)
    telephone = models.CharField(max_length=44, null=True, blank=True)
    mobile = models.CharField(max_length=44, null=True, blank=True)
    email = models.EmailField(max_length=255, null=True, blank=True)

    spouse_firstname = models.CharField(max_length=44, null=True, blank=True)
    spouse_middlename = models.CharField(max_length=44, null=True, blank=True)
    spouse_lastname = models.CharField(max_length=44, null=True, blank=True)
    spouse_extensions = models.CharField(max_length=44, null=True, blank=True)
    occupation = models.CharField(max_length=44, null=True, blank=True)
    emp_business_name = models.CharField(max_length=44, null=True, blank=True)
    business_address = models.CharField(max_length=255, null=True, blank=True)
    business_telephone = models.CharField(max_length=44, null=True, blank=True)
    father_firstname = models.CharField(max_length=44, null=True, blank=True)
    father_middlename = models.CharField(max_length=44, null=True, blank=True)
    father_lastname = models.CharField(max_length=44, null=True, blank=True)
    father_extensions = models.CharField(max_length=44, null=True, blank=True)
    mother_firstname = models.CharField(max_length=44, null=True, blank=True)
    mother_middlename = models.CharField(max_length=44, null=True, blank=True)
    mother_lastname = models.CharField(max_length=44, null=True, blank=True)
    mother_extensions = models.CharField(max_length=44, null=True, blank=True)
    children1 = models.CharField(max_length=100, null=True, blank=True)
    children1_dob = models.DateField(null=True, blank=True)
    children2 = models.CharField(max_length=100, null=True, blank=True)
    children2_dob = models.DateField(null=True, blank=True)
    children3 = models.CharField(max_length=100, null=True, blank=True)
    children3_dob = models.DateField(null=True, blank=True)
    children4 = models.CharField(max_length=100, null=True, blank=True)
    children4_dob = models.DateField(null=True, blank=True)

    def __str__(self) :
        return self.lastname